apiVersion: v1
kind: Namespace
metadata:
  name: recetario
---
# METADATA
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-grpc
  namespace: recetario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-grpc
  template:
    metadata:
      labels:
        app: metadata-grpc
    spec:
      containers:
      - name: metadata-grpc
        image: recetario-metadata-grpc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-grpc
  namespace: recetario
spec:
  type: ClusterIP
  selector:
    app: metadata-grpc
  ports:
  - name: grpc
    port: 9091
    targetPort: 9091
---
# RATING
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-grpc
  namespace: recetario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-grpc
  template:
    metadata:
      labels:
        app: rating-grpc
    spec:
      containers:
      - name: rating-grpc
        image: recetario-rating-grpc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: rating-grpc
  namespace: recetario
spec:
  type: ClusterIP
  selector:
    app: rating-grpc
  ports:
  - name: grpc
    port: 9092
    targetPort: 9092
---
# RECIPE (expuesto)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-grpc
  namespace: recetario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-grpc
  template:
    metadata:
      labels:
        app: recipe-grpc
    spec:
      containers:
      - name: recipe-grpc
        image: recetario-recipe-grpc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9093
        env:
        - name: ADDR_GRPC
          value: ":9093"
        - name: METADATA_ADDR
          value: "metadata-grpc:9091"
        - name: RATING_ADDR
          value: "rating-grpc:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-grpc
  namespace: recetario
spec:
  type: LoadBalancer
  selector:
    app: recipe-grpc
  ports:
  - name: grpc
    port: 9093
    targetPort: 9093
---
# HPA para recipe
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recipe-grpc-hpa
  namespace: recetario
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recipe-grpc
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50